EnableImagePreviewing: false

themes:
  - name: "windwaker"
    colors:
    - "#111716"
    - "#121918"
    - "#141c1a"
    - "#161f1d"
    - "#17211f"
    - "#182120"
    - "#192322"
    - "#1a2322"
    - "#1b2624"
    - "#1c2625"
    - "#1d332c"
    - "#1f3830"
    - "#223d34"
    - "#23302e"
    - "#253331"
    - "#27443b"
    - "#2d3d3b"
    - "#364947"
    - "#384c4a"
    - "#405654"
    - "#455e5c"
    - "#4b6663"
    - "#516d6b"
    - "#567971"
    - "#5d8d7f"
    - "#61a090"
    - "#69c4a2"
    - "#73d3b0"
    - "#78d3b6"
    - "#7ad6b9"
    - "#7aefc4"
    - "#7fe0c1"
    - "#85eaca"
    - "#87edcc"
    - "#88efcf"
    - "#8af2d1"
    - "#8bf6d4"
