[global]
progress_full_character = "="
progress_empty_character = "="
progress_prefix = "["
progress_suffix = "]"
time_format = "%Y-%m-%d %H:%M:%S"
show_legacy_warning = false

[uptime]
prefix = "Up"

[filesystems]
root = "/"
home = "/home"

[memory]
swap_pos = "beside"

[last_run]
